FROM ubuntu:22.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get -y upgrade \
    && apt-get install -y curl \
    && apt-get install -y python3 python3-dev python3-distutils 

## Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py

## Install dependencies
RUN pip3 install kaggle pandas numpy pyarrow

COPY preprocess_bank_b.py preprocess_bank_b.py