FROM ubuntu:20.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get -y upgrade \
    && apt-get install -y curl \
    && apt-get install -y python3.9 python3.9-dev python3.9-distutils

## Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.9 get-pip.py

# Install CPU-only version of PyTorch
RUN pip3 install torch --index-url https://download.pytorch.org/whl/cpu
# RUN pip3 install torch
RUN pip3 install transformers peft bitsandbytes pathlib
# RUN pip3 install transformers peft pathlib

# ENV CUDA_VISIBLE_DEVICES=""

COPY load_base_model.py load_base_model.py