FROM ubuntu:20.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get upgrade && apt-get update \
    && apt-get install -y python3 python3-pip

RUN pip3 install datasets pandas pathlib

COPY load_medquad_dataset.py load_medquad_dataset.py