FROM ubuntu:22.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get upgrade && apt-get update \
    && apt-get install -y python3 python3-pip \
    && apt-get install -y openjdk-17-jdk

RUN pip3 install pyspark pandas

ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64/
RUN export JAVA_HOME

COPY preprocess_index.py preprocess_index.py 
