FROM ubuntu:20.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get -y upgrade \
    && apt-get install -y gcc g++ curl \
    && apt-get install -y python3.9 python3.9-dev python3.9-distutils

## Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.9 get-pip.py

## Install dependencies
RUN pip3 --default-timeout=1000 install pandas torch onnx onnx2pytorch scikit-learn scipy matplotlib

COPY ccr_dpsgd_model_saving_template_v2.py ccr_dpsgd_model_saving_template_v2.py
