FROM ubuntu:22.04

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get -y upgrade \
    && apt-get install -y gcc g++ curl \
    && apt-get install -y python3 python3-dev python3-distutils

## Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py

## Install dependencies
RUN pip3 install torch --index-url https://download.pytorch.org/whl/cpu
RUN pip3 --default-timeout=1000 install pandas onnx scikit-learn scipy matplotlib

COPY save_base_model.py save_base_model.py
