FROM alpine:3.17.1

RUN apk update && apk add cryptsetup fuse curl python3 git jq
RUN python3 -m ensurepip

# Install encrypted file system binaries
COPY external/confidential-sidecar-containers/bin/azmount external/confidential-sidecar-containers/bin/remotefs external/confidential-sidecar-containers/bin/get-snp-report /bin/
COPY src/encfs/encfs.sh /
RUN chmod +x /*.sh; date > /made-date

# Install contract ledger client
COPY external/contract-ledger/pyscitt/dist/pyscitt-0.0.1-py3-none-any.whl .
RUN pip3 install pyscitt-0.0.1-py3-none-any.whl

# Install OPA and copy policy
RUN wget -O opa https://github.com/open-policy-agent/opa/releases/download/v0.53.0/opa_linux_amd64_static
RUN chmod 755 ./opa
COPY src/policy/policy.rego .
