# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy COVID scenario in Docker

on: [workflow_dispatch]

#env:
#  CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}

jobs:
  deploy-ccr-covid:
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v3

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
	  registry: ispirt.azurecr.io 
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_ACCESS_TOKEN }}

      - name: Add user to docker group
        run: sudo usermod -aG docker $USER

      - name: Pull container images
        run: cd ${{ github.workspace }}/ci && ./pull-containers.sh

      - name: Run pre-processing
        run: cd ./scenarios/covid/deployment/docker && ./preprocess.sh

      - name: Run model saving
        run: cd ./scenarios/covid/deployment/docker && ./save-model.sh
        
      - name: Run training
        run: cd ./scenarios/covid/deployment/docker && ./train.sh
